- name: variables
  hosts: local
  connection: local
  # vars: # play level variables
  #   GREET: "PLAY"
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: GREET
  #   prompt: enter the value
  #   private: false
  tasks: 
  - name: print the variables
    # vars:
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{GREET}}"

#preferences:
#1 command line  
#2 task level    
#3 Files
#4 Prompt
#5 PLAY
